### ISSUE TITLE
Can't search anything in search box

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko-site#74]
![image](https://github.com/apache/incubator-pekko-site/assets/501740/3f63943e-0efa-4c1b-ad13-edf0fc5b361c)

The issue is when you type something like `actor` and click `enter` nothing happened. seems the index is not generated.

**Comment by pjfanning** [comment]
unfortunately, the search only works when you use docs in the right area - the search data is built by all our different doc builds - each repo has its own doc build

* https://pekko.apache.org/docs/pekko/current/ has the docs for https://github.com/apache/incubator-pekko
* https://pekko.apache.org/docs/pekko-http/current/ has the docs for https://github.com/apache/incubator-pekko-http

So the search in https://pekko.apache.org/docs/pekko/current/ will support searching for actor and stream, etc.

**Comment by samueleresca** [comment]
I think the root cause it is the error on the js execution of the page:

```
application.583bbe55.js:6 Uncaught ReferenceError
    at new e (application.583bbe55.js:6:41176)
    at Object.i [as initialize] (application.583bbe55.js:6:5730)
    at (index):352:13
```

I think the error block all the subsequent js exectution. The `application.js` expect a specific structure for the  `md-header-nav__title` with multiple nested childs.

I think I have a general idea on how to fix it and make search work, but my week look busy so I'm expecting to have time only throwards the end of the week / weekend.

**Comment by pjfanning** [comment]
I guess #80 fixes the immediate issue but https://github.com/apache/incubator-pekko-site/issues/74#issuecomment-1907836509 is still an issue

**Comment by samueleresca** [comment]
> unfortunately, the search only works when you use docs in the right area - the search data is built by all our different doc builds - each repo has its own doc build
> 
> * https://pekko.apache.org/docs/pekko/current/ has the docs for https://github.com/apache/incubator-pekko
> * https://pekko.apache.org/docs/pekko-http/current/ has the docs for https://github.com/apache/incubator-pekko-http
> 
> So the search in https://pekko.apache.org/docs/pekko/current/ will support searching for actor and stream, etc.

@pjfanning  I'm opening another issue for this one, it might require a little bit of thinking
